[project]
name = "Mg132-Timecourse"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jan Eglinger <jan.eglinger@fmi.ch>"]
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64", "win-64"]

[system-requirements]
# See https://pixi.sh/latest/features/system_requirements/#default-system-requirements

[tasks]
cache_status = "python -m faim_ipa.pixi.cache_status"
source_status = "python -m faim_ipa.pixi.src_status source"
log_commit = {cmd = 'python -m faim_ipa.pixi.log_commit $TASK', env = {TASK = ""}}

[tasks.config]
cmd = "mkdir -p $WD ; TASK=CONFIG pixi run log_commit ; cd $WD ; python ../../source/config.py"
depends_on=["cache_status", "source_status"]
env = { WD = "runs/example"}

[tasks.s01_segmentation]
cmd = "mkdir -p $WD ; TASK=SEGMENT_NUCLEI pixi run log_commit ; cd $WD ; python ../../source/s01_segmentation.py"
depends_on=["cache_status", "source_status"]
env = { WD = "runs/example"}

[tasks.s02_aggresomes]
cmd = "mkdir -p $WD ; TASK=SEGMENT_AGGRESOMES pixi run log_commit ; cd $WD ; python ../../source/s02_aggresomes.py"
depends_on=["cache_status", "source_status"]
env = { WD = "runs/example"}

[dependencies]
python = "3.12"
cuda = {version = "*", channel = "nvidia/label/cuda-11.8.0"}
pytorch-cuda = {version = "11.8.*", channel = "pytorch"}
faim-ipa = ">=0.9.2,<0.10"
tifffile = ">=2024.8.24,<2025"
cellpose = ">=3.0.11,<4"
questionary = ">=2.0.1,<3"
xarray = ">=2024.9.0,<2025"
rich = ">=13.9.4,<14"

[feature.docs.dependencies]
mkdocs = ">=1.6.0,<2"
mkdocs-git-committers-plugin-2 = ">=2.3.0,<3"
mkdocs-git-revision-date-localized-plugin = ">=1.2.6,<2"
mkdocs-material = ">=9.5.31,<10"
mkdocstrings = ">=0.25.2,<0.26"
mkdocstrings-python = ">=1.10.7,<2"

[feature.docs.tasks]
clean_docs = "rm -rf site"
build_docs = {cmd = "OFFLINE=TRUE mkdocs build", depends_on = ["clean_docs"]}
show_docs = "mkdocs serve"

[feature.dev.dependencies]
pre-commit = ">=3.1.1,<3.8"

[feature.dev.tasks]
install_hooks = "pre-commit install"
lint = {cmd = "pre-commit run --all-files", depends_on = ["install_hooks"]}

[feature.dev.pypi-dependencies]
toml-sort = ">=0.24.2, <0.25"

[feature.jupyter.dependencies]
jupyter = ">=1.0.0,<1.1"

[feature.jupyter.tasks]
jupyter = "jupyter lab"

[environments]
default = {solve-group = "default"}
docs = {features = ["docs"], solve-group = "default"}
dev = {features = ["dev"], solve-group = "default"}
jupyter = {features = ["jupyter"], solve-group = "default"}

[pypi-dependencies]
metamorph-mda-parser = ">=0.1.2, <0.2"
