[project]
name = "Mg132 Timecourse"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jan Eglinger <jan.eglinger@fmi.ch>"]
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64", "win-64"]

[system-requirements]
# Minimum linux version for this project to work.
# This is necessary of some HPC setups, which run on e.g. Rocky Linux 8.
linux="4.18"

[tasks]
cache_status = "python -m faim_ipa.pixi.cache_status"
source_status = "python -m faim_ipa.pixi.src_status source"
log_commit = {cmd = 'python -m faim_ipa.pixi.log_commit $TASK', env = {TASK = ""}}
build_config = { cmd = "mkdir -p $WD ; TASK=BUILD_CONFIG pixi run log_commit ; cd $WD ; echo 'Implementation Missing.'", env = { WD = "runs/example"}, depends_on=["cache_status", "source_status"]}

[dependencies]
python = "3.12"
cuda = {version = "*", channel="nvidia/label/cuda-11.8.0"}
pytorch-cuda = {version = "11.8.*", channel="pytorch"}
faim-ipa = ">=0.6.0,<0.7"
tifffile = ">=2024.8.24,<2025"
cellpose = ">=3.0.11,<4"

[feature.docs.dependencies]
mkdocs = ">=1.6.0,<2"
mkdocs-git-committers-plugin-2 = ">=2.3.0,<3"
mkdocs-git-revision-date-localized-plugin = ">=1.2.6,<2"
mkdocs-material = ">=9.5.31,<10"
mkdocstrings = ">=0.25.2,<0.26"
mkdocstrings-python = ">=1.10.7,<2"

[feature.docs.tasks]
clean_docs = "rm -rf site"
build_docs = { cmd ="OFFLINE=TRUE mkdocs build", depends_on=["clean_docs"] }
show_docs = "mkdocs serve"

[feature.dev.dependencies]
pre-commit = ">=3.1.1,<3.8"

[feature.dev.tasks]
install_hooks = "pre-commit install"
lint = { cmd="pre-commit run --all-files", depends_on=["install_hooks"] }

[feature.jupyter.dependencies]
jupyter = ">=1.0.0,<1.1"

[feature.jupyter.tasks]
jupyter = "jupyter lab"

[feature.nbdev.dependencies]
nbdev = ">=2.2.10,<2.3"

[feature.nbdev.tasks]
clean = "nbdev_clean --clear_all"

[environments]
docs = ["docs"]
dev = ["dev"]
jupyter = ["jupyter"]
nbdev = {features=["nbdev"], no-default-feature = true}

[pypi-dependencies]
metamorph-mda-parser = ">=0.0.2, <0.0.3"
